### ISSUE TITLE
CLC - Clear Carry Flag instruction

### ISSUE THREAD

**Issue by yehia67** [tonk-gg/dappicom#15]
Hello, I am planning to work on the CLC instruction, 
CLC is  a single bit in a system's status register that is used to indicate when an arithmetic operation, such as addition or subtraction, results in a carry-out of the most significant bit (for unsigned arithmetic) or a borrow into the most significant bit (for two's complement arithmetic).

Example
```
 Adding 1 to 255
  11111111  (255 in binary)
+ 00000001  (1 in binary)
----------
1 00000000  (Carry out, resulting in 256 in binary, or 0x100 in hexadecimal)

```
[CLC - Clear Carry Flag instruction Reference](https://www.nesdev.org/obelisk-6502-guide/reference.html#AND)

**Comment by goblinoats** [comment]
This has been completed already by @Prabhat1308 alongside the other clear instructions. Please take a look at others you can possible take-up.
